name: next js build with chache and artifects

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.1

      - name: node js
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 22.x
          cache: 'npm'
      - name: install dependencies
        run: npm install

      - name: build next js app
        run: npm run build 

      - name: upload build in srtifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: next js build
          path: out/

      
